"""
Export service for generating PDF and DOCX documents from NeuralDocs output.
"""
import io
import re
from datetime import datetime

# ── PDF (reportlab) ──────────────────────────────────────────────────────────
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable, ListFlowable, ListItem
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import os

# Register Cyrillic fonts (these must be installed in the Docker image via fonts-dejavu-core)
try:
    pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'))
    pdfmetrics.registerFont(TTFont('DejaVuSans-Bold', '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'))
    DEFAULT_FONT = 'DejaVuSans'
    DEFAULT_FONT_BOLD = 'DejaVuSans-Bold'
except Exception as e:
    # Fallback to default if not found (e.g., local testing without the fonts installed)
    DEFAULT_FONT = 'Helvetica'
    DEFAULT_FONT_BOLD = 'Helvetica-Bold'
    print(f"Warning: Could not load DejaVuSans fonts: {e}")

# ── DOCX (python-docx) ──────────────────────────────────────────────────────
from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE


# ═════════════════════════════════════════════════════════════════════════════
# LABELS (RU / EN / KZ)
# ═════════════════════════════════════════════════════════════════════════════
LABELS = {
    "ru": {
        "title": "Проектная документация",
        "subtitle": "Сгенерировано NeuralDocs AI",
        "toc": "Содержание",
        "project_overview": "Обзор проекта",
        "goals": "Цели проекта",
        "requirements": "Требования",
        "technical_solution": "Техническое решение",
        "architecture": "Архитектура",
        "team": "Команда",
        "timeline": "Сроки",
        "budget": "Бюджет",
        "risks": "Риски",
        "conflicts": "Обнаруженные конфликты",
        "metadata": "Статистика обработки",
        "source": "Источник",
        "conflict_label": "⚠ Конфликт",
        "no_data": "Нет данных",
        "generated": "Дата генерации",
        "model": "Модель",
        "tokens": "Токенов",
        "duration": "Время обработки",
        "files": "Файлов проанализировано",
        "timeline_budget": "Сроки и Бюджет",
    },
    "en": {
        "title": "Project Documentation",
        "subtitle": "Generated by NeuralDocs AI",
        "toc": "Table of Contents",
        "project_overview": "Project Overview",
        "goals": "Project Goals",
        "requirements": "Requirements",
        "technical_solution": "Technical Solution",
        "architecture": "Architecture",
        "team": "Team",
        "timeline": "Timeline",
        "budget": "Budget",
        "risks": "Risks",
        "conflicts": "Detected Conflicts",
        "metadata": "Processing Statistics",
        "source": "Source",
        "conflict_label": "⚠ Conflict",
        "no_data": "No data",
        "generated": "Generated on",
        "model": "Model",
        "tokens": "Tokens",
        "duration": "Processing time",
        "files": "Files analyzed",
        "timeline_budget": "Timeline & Budget",
    },
}
LABELS["kz"] = LABELS["ru"]  # Kazakh uses same labels as Russian for now


def _get_labels(lang: str) -> dict:
    return LABELS.get(lang, LABELS["ru"])


def _fact_text(fact) -> str:
    """Extract text from a fact (string or {text: ...} dict)."""
    if isinstance(fact, str):
        return fact.strip()
    if isinstance(fact, dict):
        return (fact.get("text") or "").strip()
    return str(fact or "").strip()


def _fact_source(fact) -> str:
    if isinstance(fact, dict):
        return (fact.get("source") or "").strip()
    return ""


def _fact_conflict(fact) -> tuple:
    """Return (has_conflict: bool, details: str)."""
    if isinstance(fact, dict):
        return bool(fact.get("has_conflict")), (fact.get("conflict_details") or "")
    return False, ""


# ═════════════════════════════════════════════════════════════════════════════
# PDF GENERATION
# ═════════════════════════════════════════════════════════════════════════════

# Color palette
_PRIMARY = colors.HexColor("#4F46E5")
_GREEN = colors.HexColor("#10B981")
_ORANGE = colors.HexColor("#F59E0B")
_DARK = colors.HexColor("#1F2937")
_MUTED = colors.HexColor("#6B7280")
_LIGHT_BG = colors.HexColor("#F9FAFB")
_CONFLICT_BG = colors.HexColor("#FEF3C7")
_SOURCE_BG = colors.HexColor("#DBEAFE")
_WHITE = colors.white


def generate_pdf(data: dict, language: str = "ru") -> bytes:
    """Generate a professional PDF from NeuralDocs output. Returns PDF bytes."""
    L = _get_labels(language)
    doc_data = data.get("document_extended") or data.get("document", {})
    meta = data.get("metadata", {})

    buf = io.BytesIO()
    pdf = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=2 * cm, bottomMargin=2 * cm,
        leftMargin=2.5 * cm, rightMargin=2.5 * cm,
        title=L["title"],
        author="NeuralDocs AI",
    )

    styles = getSampleStyleSheet()

    # Custom styles
    s_title = ParagraphStyle(
        "NDTitle", parent=styles["Title"],
        fontName=DEFAULT_FONT_BOLD,
        fontSize=28, textColor=_PRIMARY, spaceAfter=6 * mm,
        alignment=TA_CENTER,
    )
    s_subtitle = ParagraphStyle(
        "NDSubtitle", parent=styles["Normal"],
        fontName=DEFAULT_FONT,
        fontSize=12, textColor=_MUTED, alignment=TA_CENTER,
        spaceAfter=4 * mm,
    )
    s_h2 = ParagraphStyle(
        "NDH2", parent=styles["Heading2"],
        fontName=DEFAULT_FONT_BOLD,
        fontSize=16, textColor=_PRIMARY, spaceBefore=10 * mm,
        spaceAfter=4 * mm, borderWidth=0,
    )
    s_body = ParagraphStyle(
        "NDBody", parent=styles["Normal"],
        fontName=DEFAULT_FONT,
        fontSize=10, leading=14, textColor=_DARK,
        alignment=TA_JUSTIFY,
    )
    s_source = ParagraphStyle(
        "NDSource", parent=styles["Normal"],
        fontName=DEFAULT_FONT,
        fontSize=8, textColor=colors.HexColor("#1E40AF"),
        backColor=_SOURCE_BG, leftIndent=4 * mm,
    )
    s_conflict = ParagraphStyle(
        "NDConflict", parent=styles["Normal"],
        fontName=DEFAULT_FONT,
        fontSize=9, textColor=colors.HexColor("#92400E"),
        backColor=_CONFLICT_BG, leftIndent=4 * mm,
        spaceBefore=2 * mm, spaceAfter=2 * mm,
        borderWidth=0.5, borderColor=_ORANGE, borderPadding=4,
    )
    s_meta = ParagraphStyle(
        "NDMeta", parent=styles["Normal"],
        fontName=DEFAULT_FONT,
        fontSize=9, textColor=_MUTED,
    )

    story = []

    # ── Cover page ───────────────────────────────────────────────────────
    story.append(Spacer(1, 60 * mm))
    story.append(Paragraph("🧠 NeuralDocs AI", s_title))
    story.append(Paragraph(L["title"], ParagraphStyle(
        "CoverTitle", parent=s_title, fontName=DEFAULT_FONT_BOLD, fontSize=20, textColor=_DARK,
    )))
    story.append(Spacer(1, 10 * mm))

    # Project name from overview
    overview = ""
    if isinstance(doc_data.get("project_overview"), str):
        overview = doc_data["project_overview"]
    elif isinstance(doc_data.get("project_overview"), dict):
        overview = doc_data["project_overview"].get("text", "")
    if overview:
        story.append(Paragraph(overview, ParagraphStyle(
            "CoverOverview", parent=s_body, fontName=DEFAULT_FONT, fontSize=11, alignment=TA_CENTER,
            textColor=_MUTED,
        )))

    story.append(Spacer(1, 20 * mm))
    story.append(HRFlowable(
        width="60%", thickness=1, color=_PRIMARY,
        spaceAfter=6 * mm, spaceBefore=6 * mm,
    ))
    now = datetime.now().strftime("%d.%m.%Y %H:%M")
    story.append(Paragraph(f"{L['generated']}: {now}", s_subtitle))
    story.append(Paragraph(
        f"{L['model']}: {meta.get('model_name', 'N/A')}",
        s_subtitle,
    ))
    story.append(PageBreak())

    # ── Helper: add a section ────────────────────────────────────────────
    def add_section(title: str, content):
        story.append(Paragraph(title, s_h2))
        story.append(HRFlowable(
            width="100%", thickness=0.5, color=colors.HexColor("#E5E7EB"),
            spaceAfter=3 * mm,
        ))
        if content is None:
            story.append(Paragraph(L["no_data"], ParagraphStyle(
                "NoData", parent=s_body, textColor=_MUTED, fontStyle="italic",
            )))
            return

        if isinstance(content, str):
            story.append(Paragraph(content or L["no_data"], s_body))
        elif isinstance(content, dict):
            # Scalar field with {text, source, has_conflict, ...}
            txt = _fact_text(content)
            story.append(Paragraph(txt or L["no_data"], s_body))
            src = _fact_source(content)
            if src:
                story.append(Paragraph(f"📄 {L['source']}: {src}", s_source))
            has_c, c_detail = _fact_conflict(content)
            if has_c and c_detail:
                story.append(Paragraph(f"{L['conflict_label']}: {c_detail}", s_conflict))
        elif isinstance(content, list):
            items = []
            for item in content:
                txt = _fact_text(item)
                if not txt:
                    continue
                # Build item paragraph
                parts = [txt]
                src = _fact_source(item)
                if src:
                    parts.append(
                        f'<font size="7" color="#1E40AF"> [{src}]</font>'
                    )
                has_c, c_detail = _fact_conflict(item)
                if has_c and c_detail:
                    parts.append(
                        f'<br/><font size="8" color="#92400E">⚠ {c_detail}</font>'
                    )
                items.append(ListItem(
                    Paragraph(" ".join(parts[:1]) + ("".join(parts[1:]) if len(parts) > 1 else ""), s_body),
                    bulletColor=_PRIMARY,
                ))
            if items:
                story.append(ListFlowable(items, bulletType='bullet', start='•'))
            else:
                story.append(Paragraph(L["no_data"], ParagraphStyle(
                    "NoData2", parent=s_body, textColor=_MUTED,
                )))

    # ── Sections ─────────────────────────────────────────────────────────
    add_section(L["project_overview"], doc_data.get("project_overview"))
    add_section(L["goals"], doc_data.get("goals"))
    add_section(L["requirements"], doc_data.get("requirements"))
    add_section(L["technical_solution"], doc_data.get("technical_solution"))
    add_section(L["architecture"], doc_data.get("architecture"))
    add_section(L["team"], doc_data.get("team"))

    # Timeline & Budget combined
    story.append(Paragraph(L["timeline_budget"], s_h2))
    story.append(HRFlowable(
        width="100%", thickness=0.5, color=colors.HexColor("#E5E7EB"),
        spaceAfter=3 * mm,
    ))

    tl = doc_data.get("timeline")
    bg = doc_data.get("budget")

    # Two-column table for timeline + budget
    tl_text = _fact_text(tl) or L["no_data"]
    bg_text = _fact_text(bg) or L["no_data"]

    tbl_data = [
        [Paragraph(f"<b>{L['timeline']}</b>", s_body),
         Paragraph(f"<b>{L['budget']}</b>", s_body)],
        [Paragraph(tl_text, s_body),
         Paragraph(bg_text, s_body)],
    ]

    # Add sources row
    tl_src = _fact_source(tl)
    bg_src = _fact_source(bg)
    if tl_src or bg_src:
        tbl_data.append([
            Paragraph(f'<font size="7" color="#1E40AF">📄 {tl_src}</font>', s_meta),
            Paragraph(f'<font size="7" color="#1E40AF">📄 {bg_src}</font>', s_meta),
        ])

    # Add conflict row if any
    tl_c, tl_cd = _fact_conflict(tl)
    bg_c, bg_cd = _fact_conflict(bg)
    if tl_c or bg_c:
        tbl_data.append([
            Paragraph(f'<font size="8" color="#92400E">⚠ {tl_cd}</font>' if tl_c else "", s_meta),
            Paragraph(f'<font size="8" color="#92400E">⚠ {bg_cd}</font>' if bg_c else "", s_meta),
        ])

    tbl = Table(tbl_data, colWidths=[pdf.width / 2] * 2)
    tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), _LIGHT_BG),
        ('TEXTCOLOR', (0, 0), (-1, 0), _PRIMARY),
        ('FONTNAME', (0, 0), (-1, -1), DEFAULT_FONT),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(tbl)

    add_section(L["risks"], doc_data.get("risks"))

    # ── Metadata footer ──────────────────────────────────────────────────
    story.append(Spacer(1, 10 * mm))
    story.append(HRFlowable(
        width="100%", thickness=1, color=_PRIMARY,
        spaceAfter=4 * mm,
    ))
    story.append(Paragraph(f"<b>{L['metadata']}</b>", ParagraphStyle(
        "MetaTitle", parent=s_body, fontName=DEFAULT_FONT_BOLD, textColor=_PRIMARY, fontSize=11,
    )))
    meta_lines = [
        f"{L['files']}: {(meta.get('llm_calls', 1)) - 1}",
        f"{L['tokens']}: {meta.get('total_tokens', 0):,}",
        f"{L['duration']}: {meta.get('duration_ms', 0):,} ms",
        f"{L['model']}: {meta.get('model_name', 'N/A')}",
    ]
    for line in meta_lines:
        story.append(Paragraph(line, s_meta))

    pdf.build(story)
    return buf.getvalue()


# ═════════════════════════════════════════════════════════════════════════════
# DOCX GENERATION
# ═════════════════════════════════════════════════════════════════════════════

def generate_docx(data: dict, language: str = "ru") -> bytes:
    """Generate a professional DOCX from NeuralDocs output. Returns DOCX bytes."""
    L = _get_labels(language)
    doc_data = data.get("document_extended") or data.get("document", {})
    meta = data.get("metadata", {})

    doc = Document()

    # ── Styles ────────────────────────────────────────────────────────────
    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(11)
    style.paragraph_format.space_after = Pt(6)

    # ── Cover page ────────────────────────────────────────────────────────
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.space_before = Pt(100)
    run = p.add_run("🧠 NeuralDocs AI")
    run.font.size = Pt(32)
    run.font.color.rgb = RGBColor(0x4F, 0x46, 0xE5)
    run.bold = True

    p2 = doc.add_paragraph()
    p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run2 = p2.add_run(L["title"])
    run2.font.size = Pt(18)
    run2.font.color.rgb = RGBColor(0x1F, 0x29, 0x37)

    # Overview on cover
    overview = ""
    if isinstance(doc_data.get("project_overview"), str):
        overview = doc_data["project_overview"]
    elif isinstance(doc_data.get("project_overview"), dict):
        overview = doc_data["project_overview"].get("text", "")
    if overview:
        p3 = doc.add_paragraph()
        p3.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p3.space_before = Pt(20)
        run3 = p3.add_run(overview)
        run3.font.size = Pt(11)
        run3.font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

    # Date & model
    p4 = doc.add_paragraph()
    p4.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p4.space_before = Pt(30)
    now = datetime.now().strftime("%d.%m.%Y %H:%M")
    run4 = p4.add_run(f"{L['generated']}: {now}\n{L['model']}: {meta.get('model_name', 'N/A')}")
    run4.font.size = Pt(9)
    run4.font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

    doc.add_page_break()

    # ── Helper: add section ──────────────────────────────────────────────
    def add_heading(title: str):
        h = doc.add_heading(title, level=2)
        for run in h.runs:
            run.font.color.rgb = RGBColor(0x4F, 0x46, 0xE5)

    def add_scalar(field):
        txt = _fact_text(field)
        if not txt:
            p = doc.add_paragraph(L["no_data"])
            p.runs[0].font.color.rgb = RGBColor(0x6B, 0x72, 0x80)
            p.runs[0].italic = True
            return

        p = doc.add_paragraph(txt)
        src = _fact_source(field)
        if src:
            run = p.add_run(f"  [{src}]")
            run.font.size = Pt(8)
            run.font.color.rgb = RGBColor(0x1E, 0x40, 0xAF)

        has_c, c_detail = _fact_conflict(field)
        if has_c and c_detail:
            cp = doc.add_paragraph()
            run = cp.add_run(f"⚠ {L['conflict_label']}: {c_detail}")
            run.font.size = Pt(9)
            run.font.color.rgb = RGBColor(0x92, 0x40, 0x0E)
            # Yellow highlight for conflict
            from docx.oxml.ns import qn
            from docx.oxml import OxmlElement
            shading = OxmlElement('w:shd')
            shading.set(qn('w:fill'), 'FEF3C7')
            shading.set(qn('w:val'), 'clear')
            run._element.rPr.append(shading)

    def add_list(items):
        if not items:
            p = doc.add_paragraph(L["no_data"])
            p.runs[0].font.color.rgb = RGBColor(0x6B, 0x72, 0x80)
            p.runs[0].italic = True
            return

        for item in items:
            txt = _fact_text(item)
            if not txt:
                continue

            p = doc.add_paragraph(txt, style='List Bullet')
            src = _fact_source(item)
            if src:
                run = p.add_run(f"  [{src}]")
                run.font.size = Pt(8)
                run.font.color.rgb = RGBColor(0x1E, 0x40, 0xAF)

            has_c, c_detail = _fact_conflict(item)
            if has_c and c_detail:
                run = p.add_run(f"\n⚠ {c_detail}")
                run.font.size = Pt(8)
                run.font.color.rgb = RGBColor(0x92, 0x40, 0x0E)

    # ── Sections ─────────────────────────────────────────────────────────
    add_heading(L["project_overview"])
    ov = doc_data.get("project_overview")
    if isinstance(ov, str):
        doc.add_paragraph(ov or L["no_data"])
    else:
        add_scalar(ov)

    add_heading(L["goals"])
    add_list(doc_data.get("goals"))

    add_heading(L["requirements"])
    add_list(doc_data.get("requirements"))

    add_heading(L["technical_solution"])
    add_scalar(doc_data.get("technical_solution"))

    add_heading(L["architecture"])
    add_scalar(doc_data.get("architecture"))

    add_heading(L["team"])
    add_list(doc_data.get("team"))

    add_heading(L["timeline_budget"])
    tl = doc_data.get("timeline")
    bg = doc_data.get("budget")

    # Timeline
    p = doc.add_paragraph()
    run = p.add_run(f"{L['timeline']}: ")
    run.bold = True
    run = p.add_run(_fact_text(tl) or L["no_data"])
    tl_src = _fact_source(tl)
    if tl_src:
        run = p.add_run(f"  [{tl_src}]")
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x1E, 0x40, 0xAF)

    tl_c, tl_cd = _fact_conflict(tl)
    if tl_c and tl_cd:
        cp = doc.add_paragraph()
        run = cp.add_run(f"⚠ {tl_cd}")
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0x92, 0x40, 0x0E)

    # Budget
    p = doc.add_paragraph()
    run = p.add_run(f"{L['budget']}: ")
    run.bold = True
    run = p.add_run(_fact_text(bg) or L["no_data"])
    bg_src = _fact_source(bg)
    if bg_src:
        run = p.add_run(f"  [{bg_src}]")
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x1E, 0x40, 0xAF)

    bg_c, bg_cd = _fact_conflict(bg)
    if bg_c and bg_cd:
        cp = doc.add_paragraph()
        run = cp.add_run(f"⚠ {bg_cd}")
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0x92, 0x40, 0x0E)

    add_heading(L["risks"])
    add_list(doc_data.get("risks"))

    # ── Metadata ─────────────────────────────────────────────────────────
    doc.add_page_break()
    add_heading(L["metadata"])
    meta_lines = [
        f"{L['files']}: {(meta.get('llm_calls', 1)) - 1}",
        f"{L['tokens']}: {meta.get('total_tokens', 0):,}",
        f"{L['duration']}: {meta.get('duration_ms', 0):,} ms",
        f"{L['model']}: {meta.get('model_name', 'N/A')}",
    ]
    for line in meta_lines:
        p = doc.add_paragraph(line)
        p.runs[0].font.size = Pt(9)
        p.runs[0].font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
